### ISSUE TITLE
Timing issue

### ISSUE THREAD

**Issue by d2tehp** [maxmetcalfe/Fog-City-Run-2.0#40]
I noticed that the race report timing came back with an error showing my time being 1 second after another runner who actually finished 1 second slower than me. 

Please fix

**Comment by maxmetcalfe** [comment]
Thanks for reporting an issue! Unfortunately, we have received several reports from the field that this runner did indeed finish ahead of you by 1 second. Therefore, I'm unable to modify your time. A workaround for the future is to run 1 second or more faster than the other runner which will place you ahead of that runner at the finish line and in the results at the end of the race.
